defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "page"

permalink: pretty

collections:
  portal-updates:
    output: true
    permalink: /:collection/:name
    default:
      layer:portal_update
  atn-updates:
    output: true
    permalink: /:collection/:name
    default:
      layer:atn_update
  ooi-updates:
    output: true
    permalink: /:collection/:name
    default:
      layer:ooi_update

host: 0.0.0.0
